### ISSUE TITLE
putting to https://pub.dev/

### ISSUE THREAD

**Issue by guyulmaz** [hanisimo/countdown_timer#1]
Hello hanisimo,
do you plan to put this as a package to https://pub.dev ?, as null safe package?
Kind regards,

**Comment by hanisimo** [comment]
Hello Göksel, 

Thank you for your message, 

Actually, no, I do not have a plan currently to put this as a null safe package to https://pub.dev. 

Thanks for asking 🙂 Best regards and have a beautiful day,

**Comment by hanisimo** [comment]
Hello Göksel,

Thank you for your message,

Actually, no, I do not have a plan currently to put this as a null safe package to https://pub.dev.

Thanks for asking 🙂 Best regards and have a beautiful day,
